// AUTO-GENERATED by scripts/sync-club-icons.mjs
// Source: /resources/*

export const CLUB_ICON_FILES = [
  "basketball-icon-01.png",
  "basketball-icon-02.png",
  "basketball-icon-03.png",
  "basketball-icon-04.png",
  "basketball-icon-05.png",
  "basketball-icon-06.png",
  "basketball-icon-07.png",
  "basketball-icon-08.png",
  "basketball-icon-09.png",
  "basketball-icon-10.png",
  "basketball-icon-11.png",
  "basketball-icon-12.png"
] as const;

export type ClubIconFile = (typeof CLUB_ICON_FILES)[number];
