'use client';

import { HistoryRecord, TeamColor } from '@/lib/types';

export default function ShareCard({
  record,
  clubName,
}: {
  record: HistoryRecord;
  clubName: string;
}) {
  return (
    <div
      style={{
        padding: '1.25rem',
        borderRadius: '16px',
        border: '1px solid rgba(255,255,255,0.12)',
        background:
          'radial-gradient(1200px 400px at 10% 0%, rgba(255,107,0,0.25), transparent 55%), radial-gradient(900px 300px at 90% 10%, rgba(59,130,246,0.18), transparent 55%), #0B0E13',
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'flex-start' }}>
        <div>
          <div style={{ fontWeight: 800, fontSize: '1.15rem', color: 'white' }}>{clubName}</div>
          <div style={{ color: 'rgba(255,255,255,0.7)', marginTop: '0.25rem' }}>
            {formatKoreanDate(record.date)}
          </div>
        </div>
        <div style={{ fontWeight: 800, color: 'rgba(255,255,255,0.85)' }}>🏀</div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: `repeat(${record.teams.length}, minmax(0, 1fr))`, gap: '0.75rem', marginTop: '1rem' }}>
        {record.teams.map((t) => (
          <div
            key={t.id}
            style={{
              borderRadius: '14px',
              border: `2px solid ${getColorHex(t.color)}`,
              background: 'rgba(0,0,0,0.25)',
              padding: '0.75rem',
              overflow: 'hidden',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
              <span style={{ width: 14, height: 14, backgroundColor: getColorHex(t.color), borderRadius: 4, border: '1px solid rgba(255,255,255,0.6)' }} />
              <div style={{ fontWeight: 800, color: 'white', fontSize: '0.95rem' }}>{t.name}</div>
            </div>

            <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: '0.25rem' }}>
              {t.members.map((m) => (
                <li key={m.id} style={{ color: 'rgba(255,255,255,0.8)', fontSize: '0.85rem', display: 'flex', justifyContent: 'space-between', gap: '0.5rem' }}>
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{m.name}</span>
                  <span style={{ color: 'rgba(255,255,255,0.55)', flex: 'none' }}>{m.position}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <div style={{ marginTop: '1rem', color: 'rgba(255,255,255,0.55)', fontSize: '0.8rem' }}>
        Generated by Basketball Club App
      </div>
    </div>
  );
}

function formatKoreanDate(dateIso: string) {
  return new Date(dateIso).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'short',
  });
}

function getColorHex(color: TeamColor): string {
  const colorMap: Record<TeamColor, string> = {
    White: '#FFFFFF',
    Black: '#333333',
    Red: '#EF4444',
    Blue: '#3B82F6',
    Yellow: '#FBBF24',
    Green: '#10B981',
  };
  return colorMap[color];
}
